/*

Filename: puck_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 2 x 2
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define puck_map_width 2
#define puck_map_height 2
#define puck_map_tiles 4
#define puck_map_bytes 4


const unsigned char puck_map[4] = 
{
   0,   1,   2,   3, };

