/*

Filename: puck_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 2 x 2
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define puck_map_width 2
#define puck_map_height 2
#define puck_map_tiles 4
#define puck_map_bytes 4

extern unsigned char puck_map[];

