/*

Filename: puck_map.c 

Map SOURCE File 

 Info:
   Section       :
   Bank          : 0
   Map size      : 2 x 2
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#include <gb/metasprites.h>

#define puck_map_width 2
#define puck_map_height 2
#define puck_map_tiles 4
#define puck_map_bytes 4


/* all pucks share the same map */
const unsigned char puck_map[4] = 
{
   0,   1,   2,   3, };

const metasprite_t puck_metasprite[] = {
    {.dy=-8, .dx=-8, .dtile=0, .props=0},
    {.dy=0, .dx=8, .dtile=1, .props=0},
    {.dy=8, .dx=-8, .dtile=2, .props=0},
    {.dy=0, .dx=8, .dtile=3, .props=0},
	METASPR_TERM
};
