/*

 WINNER_LINES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __winner_lines_h_INCLUDE
#define __winner_lines_h_INCLUDE

#define winner_lines_count 3
/* Start of tile array. */
extern const unsigned char winner_lines[];

#endif

/* End of WINNER_LINES.H */
